<a href="https://colab.research.google.com/github/fkofkf431/Python-For-Data-Science/blob/main/Numpy%2CPandas%2CMatplotlib%2CSeaborn%2CScikitLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy-** (Numerical python) ek python library hai jo high performance arrays,matrix, operations aur mathematical functions provide karti hai.Data scinece me use- ML algorithms mostly numerical data ke sath kaam karte hain.Numpy ka ndarray memory efficient hota hai.Pandas,scikit learn,tensor flow sabhi numpy ke upar hi based hain.Fast mathematical operations ke liye use hoti hai,matrix/vector operations karne me use ML me,list se behtar tareeke se manipulation karti ahi.

In [2]:
import numpy as np
# Create 1D array
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
1


In [ ]:
# Create multidimensional array
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Create 3D array
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# shape and size
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)
print(arr2d.shape)
print(arr2d.size)
print(arr2d.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2


In [3]:
# Array operations(element wise)
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [8]:
# Useful array functions
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.arange(5))   # arange(start, stop, step), last will not include
print(np.arange(1,10,2))
print(np.linspace(0, 1, 5))    # linspace(start, stop, number), linspace start and end dono include karta hai,
                                #iska mtlb hai 0 se 1 ke beech 5 equal no generate kro

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]


In [12]:
# reshape and flatten
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.reshape(3,2))  # existing array ka shape change karta hai without changing the data
print(arr.reshape(6,1))   # multidimensional array banane ya karne ke liye use hota hai
# 1D array ko 2D(2 rows,3 column) bana diya
a = np.array([1,2,3,4,5,6])
print(a.reshape(2,3))
# Element ka toatl same rehna chahiye,2*3=6, nhi to error ayega,jese 2*4 nhi banega,error ayega
print(arr.flatten())     # Multidimensional array ko 1D array bana deta hai

# suppose ek image hai 28*28 pixels ki 2D image,machine learning model ko ise flatten karke 1D banana padta hai,like(0, 255, 128,...)
# Image input: reshape(28, 28), shape for visualization
# Model input: flatten(): shape(784,)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [14]:
# Random numbers
print(np.random.rand(3))  # # random floats number dega (uniform distribution use hota hai isme)
print(np.random.randint(1, 10, 3))  # 3 arndom int numbers dega 1 se 10 ke beech, 10 will not include
print(np.random.randint(10, 100, size=(2,3)))  # np.random.randint(start, end, size)

[0.21833448 0.45995312 0.20992924]
[7 3 9]
[[23 30 47]
 [65 33 63]]


In [15]:
# aggregations: kisi array ke multiple values ko ek summary value me convert karna, jese sum, mean, std, min etc.
# Ye statistics nikalne ke liye use hota hai Data science and ML me
a = np.array([1, 2, 3, 4])
print(np.sum(a))
print(np.mean(a))
print(np.std(a))

10
2.5
1.118033988749895


In [16]:
# Aggregation along axis
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(a, axis=0))  # column wise sum
print(np.sum(a, axis=1))  # row wise sum

[5 7 9]
[ 6 15]


In [17]:
# indexing and slicing numpy for 1D
a = np.array([1, 2, 3, 4])
print(a[0])
print(a[1:3])
print(a[-1])


1
[2 3]
4


In [18]:
# indexing and slicing numpy for 2D
# Slicing: [start, stop, step]
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[0, 0])  # 0 First row, 0 First column
print(a[1, 2])  # 1 second row, 2 third column
print(a[:, 1])  # slicing
print(a[1, :])

1
6
[2 5]
[4 5 6]


In [20]:
# Axis = 0 means: Operate column wise, move top to bottom
# Axis = 1 means: operate row wise, move left to right
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(np.sum(arr2d, axis=0))  # Move top to bottom and sum
print(np.sum(arr2d, axis=1))  # Move left to right and sum

[12 15 18]
[ 6 15 24]


In [21]:
# Column and row wise maximum and minimum value
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(np.max(arr2d, axis=0))
print(np.min(arr2d, axis=0))
print(np.max(arr2d, axis=1))
print(np.min(arr2d, axis=1))

[7 8 9]
[1 2 3]
[3 6 9]
[1 4 7]


In [22]:
# create a numpy array with values from 1 to 10. Reshape it in to 2*5 matrix
arr = np.arange(1, 11)
print(arr)
arr = arr.reshape(2, 5)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
# Generate a numpy array of 5 random integers between 100 and 500
arr = np.random.randint(100, 500, 5)
print(arr)

[417 390 432 367 270]


In [28]:
# find mean, median and std of array [4, 9, 1, 7,3]
arr = [4, 9, 1, 7, 3]
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.round(np.std(arr), 2))

4.8
4.0
2.85657137141714
2.86


In [29]:
# Create a 3*3 matrix filled with 1s and multiply it by 5
arr = np.random.randint(1, 10, (3, 3))
print(arr)
arr = arr * 5
print(arr)

[[8 5 9]
 [2 2 9]
 [7 8 4]]
[[40 25 45]
 [10 10 45]
 [35 40 20]]


In [40]:
# Indexing and slicing questions practice
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
# Get the element at 2nd row, 3rd column (indexing)
print(arr[1, 2])

# Get the first row
print(arr[0, :])

# Get the last column
print(arr[:, -1])

# Get the 2nd and 3rd row
print(arr[1:, :])

# Get the entire first column
print(arr[:, 0])

# Get the entire second column
print(arr[:, 1])

# Get a 2*2 subarray from top left
print(arr[:2, :2])

# Get a 2*2 subarray from bottom right
print(arr[1:, 1:])

# Get all elements from row 1 to 2(inclusive), colimn 2 to 3(inclusive)
print(arr[1:3, 1:3])

# Get the last row using negative indexing
print(arr[-1, :])

# Get the last column using negative indexing
print(arr[:, -1])

# Get the last column using slicing
print(arr[:, -1:])

# Get every alternate element from the first row
print(arr[0, ::2])

# Get every alternate element from the second row
print(arr[1, ::2])

# Get every alternate element from the third row
print(arr[2, ::2])

# Flatten the array to 1D using slicing or function
print(arr.flatten())
# OR
print(arr.reshape(-1))

70
[10 20 30 40]
[ 40  80 120]
[[ 50  60  70  80]
 [ 90 100 110 120]]
[10 50 90]
[ 20  60 100]
[[10 20]
 [50 60]]
[[ 60  70  80]
 [100 110 120]]
[[ 60  70]
 [100 110]]
[ 90 100 110 120]
[ 40  80 120]
[[ 40]
 [ 80]
 [120]]
[10 30]
[50 70]
[ 90 110]
[ 10  20  30  40  50  60  70  80  90 100 110 120]
[ 10  20  30  40  50  60  70  80  90 100 110 120]
